### ISSUE TITLE
Backup stops when a VM is removed in the meantime

### ISSUE THREAD

**Issue by Flos** [wefixit-AT/oVirtBackup#28]
If you run the backup script for all VMs, the backup fails, if during the period of backing up, a VM is removed. 

For me its ok, if that VM is not backed up, but currently the script executions ends with a 'NoneType' exception.
 
Case:
I have 22 VMs, and started a backup for all of them ( -a ), this takes on my system currently approx. 22 Hours. In the meantime someone else removed a test VM. 

Log:
```
Jan 05 19:03:45: Start backup for: Gluu2-test
Jan 05 19:03:45: !!! Got unexpected exception: 'NoneType' object has no attribute 'snapshots'
```

**Comment by lukas-bednar** [comment]
That patch just test result of vms.get() whether it is None, which should prevent the issue described above.

On other hand I think there are more places where script can fail because of removed vm.
I didn't consider them in this patch ... please feel free to review it and put comments on the places which you find problematic ... and I can put it under consideration as well .
