### ISSUE TITLE
no logs generated

### ISSUE THREAD

**Issue by paf1** [wefixit-AT/oVirtBackup#5]
Hi, 
next issue on the same version oVirt  is about logs.
We have no logs generated anywhere :-(
running on
oVirt Engine Version: 3.5.2.1-1.el7.centos

any help ??
regs.
Pavel

**Comment by wefixit-AT** [comment]
Can you please post the config (WITHOUT the password ;-) and the command how you started the backup + the oVirt SDK version and python version.
Which error code do you get back and did a backup start? Do you see created snapshot's or cloned VM's.

The backup procedure is: Create VM snapshot, Clone the snapshot into an VM, export the VM to the backup storage, delete the cloned VM.
Thats the only way with the current SDK. I would like to exports snapshot directly to save storage but thats not possible today. A direct VM backup solution is planned without the use of the SDK but this could take a long time because there are to less time to spend for this.

**Comment by paf1** [comment]
./backup.py -c config-TEST.cfg -d

I didn't get back any error, any logs, anything .

$ cat config-TEST.cfg
[config]
vm_names: ["test2","test1"]
vm_middle=_BACKUP
snapshot_description=Snapshot for backup script
server=https://ovirt
username=admin@internal
password=
export_domain=BACKUP-export
timeout=5
cluster_name=KVM-prod
backup_keep_count=21
dry_run=False

==============================================================

GUI - oVirt Engine Version: 3.5.2.1-1.el7.centos
ovirt-engine-sdk-python-3.5.5.0-1.el7.centos.noarch
python-2.7.5-18.el7_1.1.x86_64

**Comment by paf1** [comment]
The direct VM backup solution looks to be the right way ( keep human file names if possible )

**Comment by wefixit-AT** [comment]
Is this the same machine as in issue #4 ?
Which error code do you get back ? "echo $?"

**Comment by paf1** [comment]
Yes, this is the same machine as issue #4

**Comment by wefixit-AT** [comment]
Ok, because there you posted an output in the first comment and here you don't get an output with the same parameters and same config?

**Comment by paf1** [comment]
All reported issues by me are from the same server with same parameters.
Changed only names of VMs .

**Comment by wefixit-AT** [comment]
Is there any difference between the config here and from issue #4 and is there a difference in the command including the parameters?
If the are all the same then I don't understand why you get an output which you posted in issue #4 and why you don' get an output like described here.

**Comment by paf1** [comment]
there are no differences .
I thought, that all supported data are needed for each issues extra. If not, will delete duplicity

**Comment by paf1** [comment]
solved - can be closed
